<?php


namespace App\Services;


use App\Repositories\OrderRepository;

class OrderService extends BaseService
{
    protected $orderRepository, $productService;

    public function __construct(OrderRepository $orderRepository, ProductService $productService)
    {
        parent::__construct($orderRepository);
        $this->orderRepository = $orderRepository;
        $this->productService = $productService;
    }

    /**
     * return all orders with relationships
     * @return object
     */
    public function all(): object
    {
        return $this->orderRepository->findByRelations('oderItem');
    }

    public function update(int $id, array $attributes): bool
    {
        if($attributes['status'] === 'canceled'){
            //$this->productService->updateQuantify($item["product"], $item["quantaty"]);
        }
        return parent::update($id, $attributes); // TODO: Change the autogenerated stub
    }

    private function canceledItens(int $order_id){
        $order = $this->find($order_id);
    }
}
